version: "3"
services:
  appURL:
    image: appurl
    build:
      context: .
    ports:
      - "8089:8089"
    networks:
      - mynetwork
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=HRMS
    ports:
      - "3307:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
